# Generated by Django 3.2.5 on 2024-11-10 10:27

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NormalUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
            ],
        ),
        migrations.CreateModel(
            name='Establishment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225, verbose_name='Nom')),
                ('manager_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom du manager')),
                ('foundation_date', models.DateField(blank=True, null=True, verbose_name='Date de fondation')),
                ('address', models.CharField(max_length=100, verbose_name='Adresse')),
                ('nif_cin', models.CharField(max_length=9, null=True, verbose_name='NIF_CIN')),
                ('rc_license', models.CharField(blank=True, max_length=12, null=True, verbose_name='RC')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(null=True, upload_to='images/establishments', verbose_name='Photo de couverture')),
                ('establishment_type', models.CharField(blank=True, choices=[('type1', 'Type 1'), ('type2', 'Type 2')], max_length=100, verbose_name="Type d'établissement")),
                ('latitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('is_verified', models.BooleanField(default=False, verbose_name='Vérifié par Foulanzam')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('is_open', models.BooleanField(default=True, verbose_name='Ouvert')),
                ('is_managed', models.BooleanField(default=False, verbose_name='Géré par Foulanzam')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='establishments', to='dashboard.normaluser', verbose_name='Propriétaire')),
            ],
        ),
    ]
