# Generated by Django 3.2.5 on 2024-11-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_usergroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='phone_number',
            field=models.CharField(default='1234567890', max_length=20, verbose_name='Numéro de téléphone'),
        ),
        migrations.AlterField(
            model_name='establishment',
            name='phone_number',
            field=models.CharField(default='1234567890', max_length=20, verbose_name='Numéro de téléphone'),
        ),
    ]
