# Generated by Django 3.2.5 on 2024-11-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20241112_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='command',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
