# Generated by Django 3.2.5 on 2024-11-12 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_alter_command_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Command',
        ),
    ]
