# Generated by Django 3.2.5 on 2024-11-12 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_delete_command'),
    ]

    operations = [
        migrations.CreateModel(
            name='Command',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('en cours', 'En Cours'), ('annulé', 'Annulé'), ('livré', 'Livré')], max_length=20)),
                ('created_at', models.DateField()),
            ],
        ),
    ]
