# Generated by Django 3.2.5 on 2024-11-16 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_command'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='phone_number',
            field=models.CharField(default='', max_length=20, verbose_name='Numéro de téléphone'),
        ),
    ]
