# Generated by Django 3.2.5 on 2024-12-21 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_auto_20241220_0153'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='normaluser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='normaluser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='address',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='normaluser',
            name='user_permissions',
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='normaluser',
            name='username',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('users', models.ManyToManyField(related_name='groups', to='dashboard.NormalUser')),
            ],
        ),
    ]
