# Generated by Django 3.2.5 on 2024-12-22 00:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0011_auto_20241221_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='normaluser',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='auth.group'),
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
